/**
 * Madani mushaf page layouts (1405H / 1421H / 1441H) + the word index that
 * resolves their Digital Khatt word ids to text and `s:a:w` locations.
 *
 * Layout files are generated by `scripts/codegen/build_mushaf_layouts.py` and
 * lazy-imported per print year (a JS chunk, so no binary asset to ship). A
 * line only carries a word-id range — text comes from the DK script the tab
 * already loads (`loadDk()`), whose ids match the layout's (verse-end markers
 * included, as their own words).
 */
import { loadDk } from '../../../lib/recitation-data/ts-source';
import type { MushafYear } from '../stores/mushaf';

export const PAGE_COUNT = 604;
export const LINES_PER_PAGE = 15;

export const LINE_AYAH = 0;
export const LINE_SURAH = 1;
export const LINE_BASMALLAH = 2;

/** `[kind, centered, a, b]` — ayah: a..b word ids; surah: a = surah number. */
export type LayoutLine = [kind: number, centered: number, a: number, b: number];

export interface MushafLayout {
    year: MushafYear;
    /** 604 pages, index = page − 1. */
    pages: LayoutLine[][];
    /** Juz / hizb number per page (index = page − 1). */
    juz: number[];
    hizb: number[];
    /** First ayah-line word id per page — ascending, for page lookup. */
    pageFirstWord: number[];
}

type RawLayout = Omit<MushafLayout, 'pageFirstWord'>;

const LOADERS: Record<MushafYear, () => Promise<{ default: unknown }>> = {
    '1405': () => import('./data/layout-1405.json'),
    '1421': () => import('./data/layout-1421.json'),
    '1441': () => import('./data/layout-1441.json'),
};

const cache = new Map<MushafYear, Promise<MushafLayout>>();

export function loadLayout(year: MushafYear): Promise<MushafLayout> {
    let p = cache.get(year);
    if (!p) {
        p = LOADERS[year]().then((mod) => indexLayout(mod.default as RawLayout));
        p.catch(() => cache.delete(year)); // let a later visit retry a failed chunk
        cache.set(year, p);
    }
    return p;
}

export function indexLayout(raw: RawLayout): MushafLayout {
    const pageFirstWord = raw.pages.map((lines) => {
        const first = lines.find((l) => l[0] === LINE_AYAH);
        return first ? first[2] : Number.MAX_SAFE_INTEGER;
    });
    return { ...raw, pageFirstWord };
}

/** 1-based page holding word `id`. */
export function pageOfWord(layout: MushafLayout, id: number): number {
    const starts = layout.pageFirstWord;
    let lo = 0;
    let hi = starts.length - 1;
    while (lo < hi) {
        const mid = (lo + hi + 1) >> 1;
        if (starts[mid]! <= id) lo = mid;
        else hi = mid - 1;
    }
    return lo + 1;
}

// ---------------------------------------------------------------------------
// Spreads — a spread is the right (odd) page + the left (even) page facing it.
// ---------------------------------------------------------------------------

export const SPREAD_COUNT = PAGE_COUNT / 2;

export function spreadOfPage(page: number): number {
    return Math.floor((page - 1) / 2);
}

/** `[rightPage, leftPage]` of spread `s` (0-based). */
export function spreadPages(s: number): [number, number] {
    return [2 * s + 1, 2 * s + 2];
}

// ---------------------------------------------------------------------------
// Word index over the DK script
// ---------------------------------------------------------------------------

export interface WordIndex {
    /** id → text / location / (surah, ayah); index 0 unused. */
    text: string[];
    loc: string[];
    surah: Int16Array;
    ayah: Int16Array;
    idOfLoc: Map<string, number>;
}

interface DkEntry {
    id?: number | string;
    location?: string;
    text?: string;
}

export function buildWordIndex(dk: Record<string, DkEntry>): WordIndex {
    let maxId = 0;
    for (const e of Object.values(dk)) maxId = Math.max(maxId, Number(e.id ?? 0));
    const text: string[] = new Array(maxId + 1).fill('');
    const loc: string[] = new Array(maxId + 1).fill('');
    const surah = new Int16Array(maxId + 1);
    const ayah = new Int16Array(maxId + 1);
    const idOfLoc = new Map<string, number>();
    for (const [key, e] of Object.entries(dk)) {
        const id = Number(e.id ?? 0);
        const location = e.location ?? key;
        const [s, a] = location.split(':');
        if (!id || !s || !a) continue;
        text[id] = e.text ?? '';
        loc[id] = location;
        surah[id] = Number(s);
        ayah[id] = Number(a);
        idOfLoc.set(location, id);
    }
    return { text, loc, surah, ayah, idOfLoc };
}

let wordIndex: Promise<WordIndex> | null = null;

/** The DK word index, built once per session (83k words). */
export function loadWordIndex(): Promise<WordIndex> {
    if (!wordIndex) {
        wordIndex = loadDk().then((dk) => buildWordIndex(dk as Record<string, DkEntry>));
        wordIndex.catch(() => { wordIndex = null; });
    }
    return wordIndex;
}

/** A verse-end marker word (U+06DD + digits) — rendered, never recited. */
export function isVerseMarker(text: string): boolean {
    return text.startsWith('۝');
}

/** Surahs whose words (or header) appear on `page`. */
export function surahsOnPage(layout: MushafLayout, words: WordIndex, page: number): number[] {
    const out = new Set<number>();
    for (const [kind, , a, b] of layout.pages[page - 1] ?? []) {
        if (kind === LINE_SURAH) out.add(a);
        else if (kind === LINE_AYAH) {
            out.add(words.surah[a]!);
            out.add(words.surah[b]!);
        }
    }
    return [...out];
}

/** First word id of verse `s:a`, or 0 when unknown. */
export function firstWordOfVerse(words: WordIndex, surah: number, ayah: number): number {
    return words.idOfLoc.get(`${surah}:${ayah}:1`) ?? 0;
}
