/* AUTOGENERATED by scripts/codegen/regen_waqf_render.mjs — do not edit. */

/** Scale + nudge that centres one waqf mark's ink in a pause tile. */
export interface WaqfRender {
    /** Glyph font-size as a multiple of the word font. */
    scale: number;
    /** Horizontal nudge, em of the scaled glyph (negative is left). */
    shiftEm: number;
    /** Vertical nudge, em of the scaled glyph (negative is up). */
    raiseEm: number;
}

/**
 * Per-QPC-face calibration, keyed by SDK riwayah slug then by the mark's
 * lowercase hex codepoint.
 *
 * A mark absent from a face's entry has no glyph in that face: the browser
 * falls through the font stack to DigitalKhatt, so the cells package's own
 * DigitalKhatt calibration is the right one and the caller must defer to it.
 * Hafs is absent entirely for the same reason.
 */
export const QPC_WAQF_RENDER: Record<string, Record<string, WaqfRender>> = {
    warsh: {
        '6d6': { scale: 1.422, shiftEm: -0.107, raiseEm: 0.738 },
        '6d7': { scale: 1, shiftEm: -0.165, raiseEm: 0.688 },
        '6d8': { scale: 1.6, shiftEm: -0.13, raiseEm: 0.51 },
        '6dc': { scale: 1.255, shiftEm: 0.048, raiseEm: 0.448 },
    },
    qalun: {
        '6d6': { scale: 1.422, shiftEm: -0.107, raiseEm: 0.745 },
        '6d7': { scale: 1, shiftEm: -0.165, raiseEm: 0.695 },
        '6d8': { scale: 1.6, shiftEm: -0.13, raiseEm: 0.517 },
        '6dc': { scale: 1.255, shiftEm: 0.048, raiseEm: 0.455 },
    },
    shuba: {
        '6d6': { scale: 1, shiftEm: -0.193, raiseEm: 0.695 },
        '6d7': { scale: 1, shiftEm: -0.165, raiseEm: 0.71 },
        '6d8': { scale: 1.6, shiftEm: -0.13, raiseEm: 0.51 },
        '6da': { scale: 1.123, shiftEm: -0.128, raiseEm: 0.718 },
        '6db': { scale: 1.524, shiftEm: -0.128, raiseEm: 0.52 },
        '6dc': { scale: 1.255, shiftEm: 0.068, raiseEm: 0.438 },
    },
};
